/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const fs = require("fs");
const path = require("path");

/** changelog フォルダ内の YYYYMMDD.md ファイルを昇順ソートして最新を返す */
function getLatestChangelog() {
  const dir = path.join(__dirname, "docs", "changelog");
  return fs
    .readdirSync(dir)
    .filter((f) => /^\d{8}\.md$/.test(f))
    .map((f) => f.replace(/\.md$/, ""))
    .sort()
    .pop();
}

// 最新の日付文字列
const latest = getLatestChangelog();

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docsSidebar: [
    {
      type: "category",
      label: "Part I: Introduction",
      items: ["part-1/purpose-and-overview"],
      collapsed: false,
      collapsible: false,
    },
    {
      type: "category",
      label: "Part II: SaaS Fundamentals",
      items: [
        "part-2/what-is-saas",
        "part-2/what-is-saasus",
        "part-2/cloud-computing-basics",
        "part-2/saas-advantages-and-disadvantages",
        "part-2/saas-business-model",
        "part-2/saas-technical-architecture",
        "part-2/saas-operations",
        "part-2/saas-development",
        "part-2/saas-marketing",
        "part-2/saas-security-and-compliance",
        "part-2/saas-legal-issues",
      ],
    },
    {
      type: "category",
      label: "Part III: Overview and Setup of the SaaSus Platform",
      items: [
        "part-3/saasus-platform-architecture",
        "part-3/getting-started",
        "part-3/login-and-main-screen-overview",
      ],
    },
    {
      type: "category",
      label: "Part IV: Using the SaaSus Platform (Developer Console)",
      items: [
        "part-4/saas-development-console-overview",
        {
          type: "category",
          label: "Registering and Configuring Applications",
          link: {
            type: "generated-index",
            title: "Registering and Configuring Applications",
            description:
              "Configure various settings required to build your SaaSus Platform application.",
            slug: "/part-4/application-settings",
          },
          items: [
            "part-4/application-settings/basic-app-settings",
            "part-4/application-settings/domain-and-redirect-settings",
            "part-4/application-settings/api-key-settings",
            {
              type: "category",
              label: "Settings for Google Tag Manager",
              link: {
                type: "doc",
                id: "part-4/application-settings/googletagmanagersetting",
              },
              items: [
                "part-4/application-settings/googletagmanagersetting/googletagmanagercreateaccountandcontainer",
                "part-4/application-settings/googletagmanagersetting/googletagmanagercontaineridsetting",
                "part-4/application-settings/googletagmanagersetting/creategoogleanalyticsaccount",
                "part-4/application-settings/googletagmanagersetting/googleanalyticsgoogletagmanagerlink",
              ],
            },
            "part-4/application-settings/ip-restriction",
            "part-4/application-settings/declare-additional-attribute-to-tenant",
          ],
        },
        {
          type: "category",
          label: "Pricing & Billing",
          link: {
            type: "generated-index",
            title: "Pricing & Billing",
            description:
              "Configure pricing models, usage-based meters, tax rates, and Stripe integration for billing.",
            slug: "/part-4/pricing-and-billing",
          },
          items: [
            "part-4/pricing-and-billing/pricing-plan-overview",
            "part-4/pricing-and-billing/tiered-unit",
            "part-4/pricing-and-billing/pricing-plan-creation",
            "part-4/pricing-and-billing/tax-rate-settings",
            "part-4/pricing-and-billing/stripe-integration",
            "part-4/pricing-and-billing/usage-metering",
          ],
        },
        {
          type: "category",
          label: "User Authentication and Authorization Configuration",
          link: {
            type: "generated-index",
            title: "User Authentication and Authorization Configuration",
            description:
              "Includes settings for login methods, user attributes, environments, roles, and notification emails related to user authentication and authorization.",
            slug: "/part-4/user-authz-settings",
          },
          items: [
            {
              type: "category",
              label: "Authentication Method Settings",
              link: {
                type: "doc",
                id: "part-4/user-authz-settings/authentication-method-settings",
              },
              items: ["part-4/user-authz-settings/google-linkage"],
            },
            "part-4/user-authz-settings/declare-additional-attribute-to-user",
            "part-4/user-authz-settings/notifymailcustomize",
            "part-4/user-authz-settings/role-definition",
            "part-4/user-authz-settings/user-env-definition",
          ],
        },
        {
          type: "category",
          label: "Smart API Gateway Features",
          link: {
            type: "doc",
            id: "part-4/smart-api-gateway-features/overview",
          },
          items: [
            "part-4/smart-api-gateway-features/manual",
            "part-4/smart-api-gateway-features/smart-mcp-server-overview",
          ],
        },
        {
          type: "category",
          label: "Integrate with Amazon EventBridge",
          link: {
            type: "doc",
            id: "part-4/integrate-with-amazon-eventbridge",
          },
          items: ["part-4/integrate-with-amazon-eventbridge/event-sample"],
        },
        "part-4/single-tenant-management",
        {
          type: "category",
          label: "AWS Marketplace Integration",
          link: {
            type: "doc",
            id: "part-4/aws-marketplace-integration/aws-marketplace-integration",
          },
          items: [
            {
              type: "category",
              label: "Setting Up Disbursement methods From Seller Registration",
              link: {
                type: "doc",
                id: "part-4/aws-marketplace-integration/aws-marketplace-seller-registration",
              },
              items: [
                "part-4/aws-marketplace-integration/aws-marketplace-seller-registration/aws-marketplace-seller-registration",
                "part-4/aws-marketplace-integration/aws-marketplace-seller-registration/public-profile-settings",
                "part-4/aws-marketplace-integration/aws-marketplace-seller-registration/tax-information-interview",
                "part-4/aws-marketplace-integration/aws-marketplace-seller-registration/dac7-tax-survey",
                "part-4/aws-marketplace-integration/aws-marketplace-seller-registration/register-bank-account",
                "part-4/aws-marketplace-integration/aws-marketplace-seller-registration/register-disbursement-methods",
              ],
            },
            {
              type: "category",
              label: "Registration of SaaS Product Information",
              link: {
                type: "doc",
                id: "part-4/aws-marketplace-integration/product-submission",
              },
              items: [
                "part-4/aws-marketplace-integration/product-submission/generate-product-code",
                "part-4/aws-marketplace-integration/product-submission/step1-provide-product-information",
                "part-4/aws-marketplace-integration/product-submission/step2-configure-fulfillment-options",
                "part-4/aws-marketplace-integration/product-submission/step3-configure-product-pricing",
                "part-4/aws-marketplace-integration/product-submission/step4-set-prices",
                "part-4/aws-marketplace-integration/product-submission/step5-specify-refund-policy",
                "part-4/aws-marketplace-integration/product-submission/step6-configure-eula",
                "part-4/aws-marketplace-integration/product-submission/step7-configure-offer-availability",
                "part-4/aws-marketplace-integration/product-submission/step8-configure-allowlist",
              ],
            },
            "part-4/aws-marketplace-integration/embedding-products",
            {
              type: "category",
              label: "Supplementary",
              link: {
                type: "doc",
                id: "part-4/aws-marketplace-integration/supplementary",
              },
              items: [
                "part-4/aws-marketplace-integration/supplementary/integration-test",
                "part-4/aws-marketplace-integration/supplementary/self-up-setting",
                "part-4/aws-marketplace-integration/supplementary/user-judgment-method",
                "part-4/aws-marketplace-integration/supplementary/supplementary-1",
                "part-4/aws-marketplace-integration/supplementary/supplementary-2",
                "part-4/aws-marketplace-integration/supplementary/supplementary-3",
                "part-4/aws-marketplace-integration/supplementary/final-review-request",
                "part-4/aws-marketplace-integration/supplementary/public-request",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "SaaSus API MCP Server Usage Guide",
          link: {
            type: "doc",
            id: "part-4/mcp-server/setup",
          },
          items: [
            "part-4/mcp-server/clone-dev-settings",
            "part-4/mcp-server/export-user-info-csv",
            "part-4/mcp-server/bulk-user-registration",
            "part-4/mcp-server/environment-setup-guide",
          ],
        },
        {
          type: "category",
          label: "Account Settings",
          link: {
            type: "generated-index",
            title: "Account Settings",
            description:
              "Change your account name, manage your SaaSus Platform subscription plan, and invite other users.",
            slug: "/part-4/account-settings",
          },
          items: [
            "part-4/account-settings/procedure-for-applying-for-a-paid-plan",
            "part-4/account-settings/saasususerinvitation",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Part V: Using the SaaSus Platform (Operation Console)",
      items: [
        "part-5/operations-console-overview",
        {
          type: "category",
          label: "User Management",
          link: {
            type: "generated-index",
            title: "User Management",
            description:
              "Manage users including registration, editing, and activity log review.",
            slug: "/part-5/user-management",
          },
          items: [
            "part-5/user-management/user-crud",
            "part-5/user-management/user-activity-history-log",
          ],
        },
        "part-5/tenant-management",
        "part-5/adding-role-to-user",
        {
          type: "category",
          label: "Pricing Plan Settings",
          link: {
            type: "doc",
            id: "part-5/price-plan",
          },
          items: [
            "part-5/price-plan/price-plan-setting-000",
            "part-5/price-plan/price-plan-setting-001",
            "part-5/price-plan/price-plan-setting-002",
            "part-5/price-plan/price-plan-setting-003",
            "part-5/price-plan/price-plan-setting-004",
          ],
        },
        "part-5/user-feedback",
      ],
    },
    {
      type: "category",
      label: "Part VI: Development Documentation",
      items: [
        "part-6/developer-sdk-api-overview",
        {
          type: "category",
          label: "Implementation Guide",
          link: {
            type: "generated-index",
            slug: "/part-6/implementation-guide",
            title: "Implementation Guide",
            description:
              "A collection of implementation samples built with the SaaSus SDK and API.",
          },
          items: [
            "part-6/implementation-guide/implementing-authentication-using-saasus-platform-apiserver",
            "part-6/implementation-guide/implementing-authentication-using-saasus-serverless",
            {
              type: "category",
              label:
                "Metering API Implementation Sample and Examples of Use (Laravel)",
              link: {
                type: "doc",
                id: "part-6/implementation-guide/meteringapisamplelaravelandusecase",
              },
              items: [
                "part-6/implementation-guide/example-implementation-using-metering-api",
              ],
            },
            "part-6/implementation-guide/implementing-multi-factor-authentication-apiserver",
          ],
        },
        {
          type: "category",
          label: "Usecase",
          items: [
            {
              type: "category",
              label: "About SaaS User Accounts",
              link: {
                type: "doc",
                id: "part-6/usecase/about-saas-user-accounts",
              },
              items: [
                "part-6/usecase/about-saas-user-accounts/create-tenant",
                "part-6/usecase/about-saas-user-accounts/add-tenant-user",
              ],
            },
            {
              type: "category",
              label: "About Rate Plans",
              link: {
                type: "doc",
                id: "part-6/usecase/about-rate-plans",
              },
              items: [
                "part-6/usecase/about-rate-plans/basic-charge-preference",
              ],
            },
            "part-6/usecase/authentication-methods",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Part VII: Troubleshooting and Support",
      items: [
        {
          type: "category",
          label: "FAQ",
          link: {
            type: "generated-index",
            title: "Frequently Asked Questions (FAQ)",
            description:
              "Find answers to common questions about SaaSus Platform, organized by category.",
            slug: "part-7/faq",
          },
          items: [
            "part-7/faq/saasus-platform",
            "part-7/faq/billing",
            "part-7/faq/api-sdk",
          ],
        },
        "part-7/support",
      ],
    },
    {
      type: "category",
      label: "Part VIII: Appendix",
      items: [
        {
          type: "link",
          label: "Release Notes and Change History",
          href: `/docs/changelog/${latest}`,
        },
        "part-8/risk-assessment",
      ],
    },
  ],
  tutorialSidebar: [
    {
      type: "category",
      label: "Tutorial",
      items: [
        "tutorial/tutorial-introduction",
        "tutorial/prepare-the-sample-application",
        "tutorial/prepare-saasus-platform",
        "tutorial/configuring-sdk-for-saasus-platform",
        "tutorial/authentication-preference",
        {
          type: "category",
          label: "Manage Rate Plans",
          link: {
            type: "doc",
            id: "tutorial/manage-rate-plans/manage-rate-plans",
          },
          items: [
            "tutorial/manage-rate-plans/setting-measurement-units-function-menus-and-price-plans",
          ],
        },
        "tutorial/implementation-of-authorization-based-on-tenant-information",
        "tutorial/summarize",
      ],
    },
  ],

  apiDocSidebar: [
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "doc",
        id: "reference/getting-started-with-your-api",
      },
      items: [],
    },
    {
      type: "category",
      label: "API Docs",
      items: [
        "reference/auth-api",
        "reference/billing-api",
        "reference/pricing-api",
        "reference/communication-api",
        "reference/apilog-api",
        "reference/awsmarketplace-api",
        "reference/integration",
        "reference/apigateway-api",
      ],
    },
  ],
  changelogSidebar: [
    {
      type: "category",
      label: "Changelog",
      items: [
        {
          label: "2025/06/05",
          type: "doc",
          id: "changelog/20250605",
        },
        {
          label: "2025/03/14",
          type: "doc",
          id: "changelog/20250314",
        },
        {
          label: "2024/12/10",
          type: "doc",
          id: "changelog/20241210",
        },
        {
          label: "2024/11/26",
          type: "doc",
          id: "changelog/20241126",
        },
        {
          label: "2024/11/15",
          type: "doc",
          id: "changelog/20241115",
        },
        {
          label: "2024/10/29",
          type: "doc",
          id: "changelog/20241029",
        },
        {
          label: "2024/05/24",
          type: "doc",
          id: "changelog/20240524",
        },
        {
          label: "2024/04/23",
          type: "doc",
          id: "changelog/20240423",
        },
        {
          label: "2024/04/11",
          type: "doc",
          id: "changelog/20240411",
        },
        {
          label: "2024/04/02",
          type: "doc",
          id: "changelog/20240402",
        },
        {
          label: "2024/03/19",
          type: "doc",
          id: "changelog/20240319",
        },
        {
          label: "2024/03/13",
          type: "doc",
          id: "changelog/20240313",
        },
        {
          label: "2024/03/05",
          type: "doc",
          id: "changelog/20240305",
        },
        {
          label: "2023/11/23",
          type: "doc",
          id: "changelog/20231123",
        },
        {
          label: "2023/11/18",
          type: "doc",
          id: "changelog/20231118",
        },
        {
          label: "2023/11/05",
          type: "doc",
          id: "changelog/20231105",
        },
        {
          label: "2022/12/24",
          type: "doc",
          id: "changelog/20221224",
        },
        {
          label: "Welcome to SaaSus Platform",
          type: "doc",
          id: "changelog/welcome-to-saasus-platform",
        },
      ],
      collapsible: false,
    },
  ],
};

module.exports = sidebars;
