openapi: 3.0.0
info:
  description: SaaSus Billing API Schema
  version: 1.0.0
  title: SaaSus Billing API スキーマ
  contact:
    name: Anti-Pattern
servers:
  - url: https://api.saasus.io/v1/billing
    description: Production API Server
tags:
  - name: stripe
    description: stripeリソースの操作
  - name: error
    description: テスト用途のエラー
security:
  - Bearer: []
paths:
  /stripe/info:
    get:
      tags:
        - stripe
      operationId: GetStripeInfo
      summary: Stripe連携情報を取得
      description: |
        請求業務で使う外部SaaSとの連携情報を取得します。
        現在は Stripe と連携が可能です。
        連携を行わない場合は、 SaaSus SDK/API を利用して請求処理を実装する必要があります。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: Stripe連携情報
                $ref: '#/components/schemas/StripeInfo'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - stripe
      operationId: UpdateStripeInfo
      summary: Stripe連携情報を更新
      description: |
        請求業務で使う外部SaaSとの連携情報を更新します。
        現在は Stripe と連携が可能です。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStripeInfoParam'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - stripe
      operationId: DeleteStripeInfo
      summary: Stripe連携情報を削除
      description: |
        請求業務で使う外部SaaSとの連携情報を削除します。
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /errors/internal-server-error:
    get:
      tags:
        - error
      operationId: ReturnInternalServerError
      summary: ステータスコード500でサーバーエラーを返却
      description: テスト用途で使用するエンドポイントです。ステータスコード500でサーバーエラーを返却します。
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
  schemas:
    Error:
      properties:
        type:
          type: string
          description: permission_denied
        message:
          type: string
          description: Error message
      required:
        - type
        - message
    Uuid:
      type: string
      example: 69e732d6-8ecc-45c4-c2eb-8438f7ffe775
    StripeInfo:
      title: Stripe連携情報
      type: object
      properties:
        is_registered:
          type: boolean
      required:
        - is_registered
    UpdateStripeInfoParam:
      title: Stripe連携情報の更新パラメータ
      type: object
      properties:
        secret_key:
          type: string
          description: シークレットキー
          example: sk_test_09l3shTSTKHYCzzZZsiLl2vA
      required:
        - secret_key
