openapi: 3.0.0
info:
  description: SaaSus Analysis API Schema
  version: 1.0.0
  title: SaaSus Analysis API Schema
  contact:
    name: Anti-Pattern
servers:
  - url: https://api.saasus.io/v1/analysis
    description: Production API Server
tags:
  - name: userAnalysis
    description: User Behavior Analysis
    x-description-i18n:
      jpn: ユーザの行動分析
  - name: metrics
    description: Metrics Analysis
    x-description-i18n:
      jpn: メトリクス分析
security:
  - Bearer: []
paths:
  /user-behavior-day:
    put:
      tags:
        - userAnalysis
      operationId: UpdateUserBehaviorHistoriesByDay
      summary: Analysis of user behavior on the day
      x-summary-i18n:
        jpn: 当日のユーザ行動履歴を更新
      description: |
        Analysis of user behavior on the day.
      x-description-i18n:
        jpn: |
          当日のユーザ行動履歴を更新します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserBehaviorHistoriesByDayParam'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{user_id}/behavior-histories:
    get:
      tags:
        - userAnalysis
      operationId: GetUserBehaviorHistories
      summary: Acquisition of user behavior history
      x-summary-i18n:
        jpn: 過去1ヶ月のユーザ行動履歴を取得します
      description: |
        Obtain user activity history for the past month.
      x-description-i18n:
        jpn: |
          過去1ヶ月のユーザ行動履歴を取得します
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBehaviorHistories'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /metrics/aggregated:
    get:
      tags:
        - metrics
      operationId: GetAggregatedMetrics
      summary: Get aggregated metrics
      x-summary-i18n:
        jpn: 集計されたメトリクスを取得
      description: |
        Get aggregated metrics by type and date range.
      x-description-i18n:
        jpn: |
          メトリクスタイプと期間を指定して集計されたメトリクスを取得します。
      parameters:
        - $ref: '#/components/parameters/MetricsType'
        - $ref: '#/components/parameters/StartDate'
        - $ref: '#/components/parameters/EndDate'
        - $ref: '#/components/parameters/TenantIds'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedMetrics'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /metrics/page-statistics:
    get:
      tags:
        - metrics
      operationId: GetPageStatistics
      summary: Get Page Statistics
      x-summary-i18n:
        jpn: ページ統計情報を取得
      description: |
        Get page statistics for the specified period.
      x-description-i18n:
        jpn: |
          指定された期間のページ統計情報を取得します。
      parameters:
        - in: query
          name: start_timestamp
          description: Start timestamp of statistics period (UNIX timestamp)
          required: true
          schema:
            type: integer
            example: 1701388800
        - in: query
          name: end_timestamp
          description: End timestamp of statistics period (UNIX timestamp)
          required: true
          schema:
            type: integer
            example: 1704067199
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: Page Statistics
                x-title-i18n:
                  jpn: ページ統計情報
                $ref: '#/components/schemas/PageStatistics'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /userinfo/aggregated:
    get:
      tags:
        - metrics
      operationId: GetAggregatedUserInfo
      summary: Get aggregated userinfo call count
      x-summary-i18n:
        jpn: テナント別のGetUserInfo実行数を取得
      description: |
        Get aggregated userinfo API call count by date range and tenants.
      x-description-i18n:
        jpn: |
          期間とテナントIDを指定してGetUserInfo APIの日別実行数を取得します。
      parameters:
        - $ref: '#/components/parameters/StartDate'
        - $ref: '#/components/parameters/EndDate'
        - $ref: '#/components/parameters/TenantIds'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedUserInfoMetrics'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Access or authentication information to API
      x-description-i18n:
        jpn: APIへのアクセス情報または認証情報
  parameters:
    UserId:
      in: path
      name: user_id
      description: User ID
      x-description-i18n:
        jpn: ユーザーID
      schema:
        type: string
        example: f94bfffc-8be2-11ec-b41a-0242ac120004
      required: true
    MetricsType:
      in: query
      name: metrics_type
      description: Metrics type
      x-description-i18n:
        jpn: メトリクスタイプ
      required: true
      schema:
        type: string
        enum:
          - create_tenant
          - create_saas_user
          - create_tenant_user
        example: create_tenant
    StartDate:
      in: query
      name: start_date
      description: Start date (YYYY-MM-DD)
      x-description-i18n:
        jpn: 開始日（YYYY-MM-DD）
      required: true
      schema:
        type: string
        example: '2025-01-01'
    EndDate:
      in: query
      name: end_date
      description: End date (YYYY-MM-DD)
      x-description-i18n:
        jpn: 終了日（YYYY-MM-DD）
      required: true
      schema:
        type: string
        example: '2025-01-31'
    TenantIds:
      in: query
      name: tenant_ids
      description: Tenant IDs
      x-description-i18n:
        jpn: テナントID
      required: false
      schema:
        type: array
        items:
          type: string
          example: f94bfffc-8be2-11ec-b41a-0242ac120004
  schemas:
    Error:
      properties:
        type:
          type: string
          example: permission_denied
        message:
          type: string
          example: Error message
          x-example-i18n:
            jpn: エラーメッセージ
      required:
        - type
        - message
    Uuid:
      type: string
      example: 69e732d6-8ecc-45c4-c2eb-8438f7ffe775
    UpdateUserBehaviorHistoriesByDayParam:
      type: object
      properties:
        timestamp:
          title: Date subject to renewal
          x-title-i18n:
            jpn: 更新対象日
          description: Date subject to renewal
          x-description-i18n:
            jpn: 更新対象日
          type: integer
          example: 1640995200
        user_id:
          title: User ID
          x-title-i18n:
            jpn: ユーザーID
          description: User ID
          x-description-i18n:
            jpn: ユーザーID
          $ref: '#/components/schemas/Uuid'
        histories:
          type: array
          items:
            $ref: '#/components/schemas/UserBehaviorHistory'
          description: user behavior history list
          x-description-i18n:
            jpn: ユーザの行動履歴一覧
      required:
        - timestamp
        - user_id
        - histories
    UserBehaviorHistory:
      type: object
      properties:
        timestamp:
          title: operation time stamp
          x-title-i18n:
            jpn: 行動履歴のタイムスタンプ
          description: Behavior Timestamp
          x-description-i18n:
            jpn: 行動履歴のタイムスタンプ
          type: integer
          example: 1640995200
        referer:
          title: Referer
          x-title-i18n:
            jpn: リファラー
          description: URL of the request origin
          x-description-i18n:
            jpn: リクエスト元のURL
          type: string
          example: https://examaple.com/examaple
      required:
        - timestamp
        - referer
    UserBehaviorHistories:
      title: User behavior history
      x-title-i18n:
        jpn: ユーザ行動履歴
      type: object
      properties:
        histories:
          type: array
          items:
            $ref: '#/components/schemas/DailyBehaviorHistory'
          description: user behavior history list
          x-description-i18n:
            jpn: ユーザの行動履歴一覧
      required:
        - histories
    DailyBehaviorHistory:
      title: Daily Behavior History
      x-title-i18n:
        jpn: 日毎のユーザ行動履歴
      type: object
      properties:
        behaved_at:
          title: Action History Date
          x-title-i18n:
            jpn: 行動履歴日
          description: Action History Date
          x-description-i18n:
            jpn: 行動履歴日
          type: integer
          example: 1640995200
        histories:
          type: array
          items:
            $ref: '#/components/schemas/UserBehaviorHistory'
          description: user behavior history list
          x-description-i18n:
            jpn: ユーザの行動履歴一覧
      required:
        - behaved_at
        - histories
    AggregatedMetrics:
      title: Aggregated Metrics
      x-title-i18n:
        jpn: 集計されたメトリクス
      type: object
      properties:
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/DailyMetric'
          description: Daily metrics list
          x-description-i18n:
            jpn: 日別メトリクス一覧
      required:
        - metrics
    DailyMetric:
      title: Daily Metric
      x-title-i18n:
        jpn: 日別メトリクス
      type: object
      properties:
        date:
          title: Date
          x-title-i18n:
            jpn: 日付
          description: Date (YYYY-MM-DD)
          x-description-i18n:
            jpn: 日付（YYYY-MM-DD）
          type: string
          example: '2025-01-01'
        count:
          title: Count
          x-title-i18n:
            jpn: 件数
          description: Total count for the day
          x-description-i18n:
            jpn: その日の総件数
          type: integer
          example: 100
        details:
          title: Details by Tenant
          x-title-i18n:
            jpn: テナント別詳細
          description: Details by tenant ID (only for create_tenant_user)
          x-description-i18n:
            jpn: テナントID別の詳細（create_tenant_userのみ）
          type: object
          additionalProperties:
            type: integer
          example:
            19045586-d4b0-418a-8e51-b6346380cd63: 40
            fa3018b1-1be3-49ca-9ea7-d6d657d0f878: 60
      required:
        - date
        - count
    PageStatistics:
      title: Page Statistics
      x-title-i18n:
        jpn: ページ統計情報
      type: object
      properties:
        start_date:
          type: integer
          description: Start date of statistics period (UNIX timestamp)
          example: 1701388800
        end_date:
          type: integer
          description: End date of statistics period (UNIX timestamp)
          example: 1704067199
        total_page_views:
          type: integer
          description: Total page views during the period
          example: 15420
        total_unique_users:
          type: integer
          description: Number of unique users during the period
          example: 1234
        page_statistics:
          type: array
          description: Statistics for each page
          items:
            $ref: '#/components/schemas/PageStatistic'
      required:
        - start_date
        - end_date
        - total_page_views
        - total_unique_users
        - page_statistics
    PageStatistic:
      title: Page Statistic
      x-title-i18n:
        jpn: ページ統計
      type: object
      properties:
        page_url:
          type: string
          description: Page URL
          example: https://example.com/dashboard
        total_views:
          type: integer
          description: Page views
          example: 3450
        unique_users:
          type: integer
          description: Unique users
          example: 856
      required:
        - page_url
        - total_views
        - unique_users
    AggregatedUserInfoMetrics:
      title: Aggregated UserInfo Metrics
      x-title-i18n:
        jpn: 集計されたGetUserInfo実行数
      type: object
      properties:
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/DailyUserInfoMetric'
          description: Daily userinfo call count list
          x-description-i18n:
            jpn: 日別GetUserInfo実行数一覧
      required:
        - metrics
    DailyUserInfoMetric:
      title: Daily UserInfo Metric
      x-title-i18n:
        jpn: 日別GetUserInfo実行数
      type: object
      properties:
        date:
          title: Date
          x-title-i18n:
            jpn: 日付
          description: Date (YYYY-MM-DD)
          x-description-i18n:
            jpn: 日付（YYYY-MM-DD）
          type: string
          example: '2025-01-01'
        details:
          title: Details by Tenant
          x-title-i18n:
            jpn: テナント別詳細
          description: GetUserInfo call count by tenant ID
          x-description-i18n:
            jpn: テナントID別のGetUserInfo実行数
          type: object
          additionalProperties:
            type: integer
          example:
            00000000-0000-0000-0000-000000000000: 1460
            0d7de8a8-1234-5678-9abc-def012345678: 1040
            252a9f83-1234-5678-9abc-def012345678: 930
      required:
        - date
        - details
