name: Test

on:
  workflow_dispatch:
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - run: npm ci

      - name: Run status regression tests
        run: npm run test:status

      - name: Run build
        run: npm run build

      - name: Run typecheck
        run: npm run typecheck
